/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : bigint,
  'status' : { 'onLeave' : null } |
    { 'present' : null } |
    { 'late' : null } |
    { 'absent' : null },
  'workerId' : bigint,
  'date' : Time,
}
export interface Customer {
  'id' : bigint,
  'customerType' : string,
  'name' : string,
  'contactDetails' : string,
}
export interface ExpenseRecord {
  'id' : bigint,
  'date' : Time,
  'description' : string,
  'category' : ExpenseType,
  'amount' : number,
}
export type ExpenseType = { 'fertilizers' : null } |
  { 'transportation' : null } |
  { 'other' : null } |
  { 'equipment' : null } |
  { 'labor' : null } |
  { 'packaging' : null };
export interface IncomeRecord {
  'id' : bigint,
  'source' : IncomeSource,
  'date' : Time,
  'description' : string,
  'amount' : number,
}
export type IncomeSource = { 'other' : null } |
  { 'local' : null } |
  { 'market' : null } |
  { 'wholesale' : null };
export interface InventoryItem {
  'id' : bigint,
  'costPerUnit' : number,
  'name' : string,
  'itemType' : ItemType,
  'quantity' : bigint,
}
export type ItemType = { 'equipment' : null } |
  { 'peppers' : null } |
  { 'fertilizer' : null } |
  { 'pesticide' : null };
export interface Sale {
  'id' : bigint,
  'inventoryItemId' : bigint,
  'date' : Time,
  'quantity' : bigint,
  'customerId' : bigint,
  'unitPrice' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worker { 'id' : bigint, 'name' : string, 'role' : string }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[string, string, string], bigint>,
  'addExpense' : ActorMethod<[number, Time, ExpenseType, string], bigint>,
  'addIncome' : ActorMethod<[number, Time, IncomeSource, string], bigint>,
  'addInventoryItem' : ActorMethod<[string, ItemType, bigint, number], bigint>,
  'addSale' : ActorMethod<[bigint, bigint, bigint, number], bigint>,
  'addWorker' : ActorMethod<[string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerPurchaseHistory' : ActorMethod<[bigint], Array<Sale>>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getExpenseRecords' : ActorMethod<[], Array<ExpenseRecord>>,
  'getIncomeRecords' : ActorMethod<[], Array<IncomeRecord>>,
  'getInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerAttendance' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getWorkers' : ActorMethod<[], Array<Worker>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<
    [
      bigint,
      Time,
      { 'onLeave' : null } |
        { 'present' : null } |
        { 'late' : null } |
        { 'absent' : null },
    ],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInventoryItem' : ActorMethod<
    [bigint, string, ItemType, bigint, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];