/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ExpenseType = IDL.Variant({
  'fertilizers' : IDL.Null,
  'transportation' : IDL.Null,
  'other' : IDL.Null,
  'equipment' : IDL.Null,
  'labor' : IDL.Null,
  'packaging' : IDL.Null,
});
export const FarmTimeEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'workerId' : IDL.Nat,
  'arrivalTime' : IDL.Opt(IDL.Text),
  'departureTime' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'hoursOnFarm' : IDL.Opt(IDL.Float64),
  'timestamp' : IDL.Int,
  'workerName' : IDL.Text,
  'enteredBy' : IDL.Principal,
});
export const HarvestEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'plotLocation' : IDL.Text,
  'enteredBy' : IDL.Principal,
  'harvestedBy' : IDL.Text,
  'quantityKg' : IDL.Float64,
});
export const IncomeSource = IDL.Variant({
  'other' : IDL.Null,
  'local' : IDL.Null,
  'market' : IDL.Null,
  'wholesale' : IDL.Null,
});
export const ItemType = IDL.Variant({
  'equipment' : IDL.Null,
  'peppers' : IDL.Null,
  'fertilizer' : IDL.Null,
  'pesticide' : IDL.Null,
});
export const FileAttachment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Vec(IDL.Nat8),
  'inventoryItemId' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const FileAttachmentMetadata = IDL.Record({
  'id' : IDL.Nat,
  'inventoryItemId' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'inventoryItemId' : IDL.Nat,
  'date' : Time,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'enteredBy' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'customerType' : IDL.Text,
  'name' : IDL.Text,
  'enteredBy' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const Department = IDL.Record({
  'leadName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ExpenseRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'category' : ExpenseType,
  'amount' : IDL.Float64,
  'enteredBy' : IDL.Text,
});
export const IncomeRecord = IDL.Record({
  'id' : IDL.Nat,
  'source' : IncomeSource,
  'date' : Time,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
  'enteredBy' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'costPerUnit' : IDL.Float64,
  'name' : IDL.Text,
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
  'enteredBy' : IDL.Text,
});
export const PlotEntry = IDL.Record({
  'dateActivated' : Time,
  'department' : IDL.Text,
  'plotName' : IDL.Text,
});
export const MonthlyGoal = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'plotEntries' : IDL.Vec(PlotEntry),
  'actualPlots' : IDL.Nat,
  'year' : IDL.Nat,
  'targetPlots' : IDL.Nat,
});
export const WeeklyReport = IDL.Record({
  'departmentLead' : IDL.Text,
  'departmentName' : IDL.Text,
  'planForNextWeek' : IDL.Text,
  'achievements' : IDL.Text,
  'weekEnding' : Time,
  'challenges' : IDL.Text,
});
export const WorkerDailyRecord = IDL.Record({
  'workerId' : IDL.Nat,
  'arrivalTime' : IDL.Opt(Time),
  'present' : IDL.Bool,
  'departureTime' : IDL.Opt(Time),
  'date' : Time,
  'timeOnFarm' : IDL.Opt(IDL.Int),
  'enteredBy' : IDL.Text,
});
export const Worker = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'enteredBy' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addExpense' : IDL.Func(
      [IDL.Float64, Time, ExpenseType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addFarmTimeEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [FarmTimeEntry],
      [],
    ),
  'addHarvestEntry' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [HarvestEntry],
      [],
    ),
  'addIncome' : IDL.Func(
      [IDL.Float64, Time, IncomeSource, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addInventoryItem' : IDL.Func(
      [IDL.Text, ItemType, IDL.Nat, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addMonthlyGoal' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'addPlotEntry' : IDL.Func([IDL.Nat, IDL.Text, Time, IDL.Text], [], []),
  'addSale' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64], [IDL.Nat], []),
  'addWorker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'approveUser' : IDL.Func([IDL.Principal], [], []),
  'bootstrapAdminRegistration' : IDL.Func([], [], []),
  'deleteAttachment' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteFarmTimeEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteFileAttachment' : IDL.Func([IDL.Nat], [], []),
  'deleteHarvestEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteIncome' : IDL.Func([IDL.Nat], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteSale' : IDL.Func([IDL.Nat], [], []),
  'deleteWorker' : IDL.Func([IDL.Nat], [], []),
  'getAttachment' : IDL.Func([IDL.Nat], [IDL.Opt(FileAttachment)], ['query']),
  'getAttachmentsForItem' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FileAttachmentMetadata)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCustomerPurchaseHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Sale)],
      ['query'],
    ),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
  'getFarmTimeEntries' : IDL.Func([], [IDL.Vec(FarmTimeEntry)], ['query']),
  'getFarmTimeEntriesByWorker' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FarmTimeEntry)],
      ['query'],
    ),
  'getFileAttachment' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(FileAttachment)],
      ['query'],
    ),
  'getFileAttachmentMetadata' : IDL.Func(
      [],
      [IDL.Vec(FileAttachmentMetadata)],
      ['query'],
    ),
  'getHarvestEntries' : IDL.Func([], [IDL.Vec(HarvestEntry)], ['query']),
  'getIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getMonthlyGoal' : IDL.Func([IDL.Nat], [IDL.Opt(MonthlyGoal)], ['query']),
  'getMonthlyGoals' : IDL.Func([], [IDL.Vec(MonthlyGoal)], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyReports' : IDL.Func([], [IDL.Vec(WeeklyReport)], ['query']),
  'getWeeklyReportsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(WeeklyReport)],
      ['query'],
    ),
  'getWeeklyReportsByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WeeklyReport)],
      ['query'],
    ),
  'getWorkerDailyRecords' : IDL.Func(
      [],
      [IDL.Vec(WorkerDailyRecord)],
      ['query'],
    ),
  'getWorkerDailyRecordsByWorker' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WorkerDailyRecord)],
      ['query'],
    ),
  'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'initializeFixedMonthlyGoals' : IDL.Func([], [], []),
  'isAutoRegisteredAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listPendingUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'recordWorkerDay' : IDL.Func(
      [IDL.Nat, Time, IDL.Bool, IDL.Opt(Time), IDL.Opt(Time)],
      [],
      [],
    ),
  'rejectUser' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitWeeklyReport' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCustomer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Float64, Time, ExpenseType, IDL.Text],
      [],
      [],
    ),
  'updateFarmTimeEntry' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Opt(FarmTimeEntry)],
      [],
    ),
  'updateHarvestEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(HarvestEntry)],
      [],
    ),
  'updateIncome' : IDL.Func(
      [IDL.Nat, IDL.Float64, Time, IncomeSource, IDL.Text],
      [],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, ItemType, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'updateWorker' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'uploadAttachmentToItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Nat],
      [],
    ),
  'uploadFileAttachment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ExpenseType = IDL.Variant({
    'fertilizers' : IDL.Null,
    'transportation' : IDL.Null,
    'other' : IDL.Null,
    'equipment' : IDL.Null,
    'labor' : IDL.Null,
    'packaging' : IDL.Null,
  });
  const FarmTimeEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'workerId' : IDL.Nat,
    'arrivalTime' : IDL.Opt(IDL.Text),
    'departureTime' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'hoursOnFarm' : IDL.Opt(IDL.Float64),
    'timestamp' : IDL.Int,
    'workerName' : IDL.Text,
    'enteredBy' : IDL.Principal,
  });
  const HarvestEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'plotLocation' : IDL.Text,
    'enteredBy' : IDL.Principal,
    'harvestedBy' : IDL.Text,
    'quantityKg' : IDL.Float64,
  });
  const IncomeSource = IDL.Variant({
    'other' : IDL.Null,
    'local' : IDL.Null,
    'market' : IDL.Null,
    'wholesale' : IDL.Null,
  });
  const ItemType = IDL.Variant({
    'equipment' : IDL.Null,
    'peppers' : IDL.Null,
    'fertilizer' : IDL.Null,
    'pesticide' : IDL.Null,
  });
  const FileAttachment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Vec(IDL.Nat8),
    'inventoryItemId' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const FileAttachmentMetadata = IDL.Record({
    'id' : IDL.Nat,
    'inventoryItemId' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'inventoryItemId' : IDL.Nat,
    'date' : Time,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'enteredBy' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'customerType' : IDL.Text,
    'name' : IDL.Text,
    'enteredBy' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const Department = IDL.Record({
    'leadName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ExpenseRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'category' : ExpenseType,
    'amount' : IDL.Float64,
    'enteredBy' : IDL.Text,
  });
  const IncomeRecord = IDL.Record({
    'id' : IDL.Nat,
    'source' : IncomeSource,
    'date' : Time,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
    'enteredBy' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'costPerUnit' : IDL.Float64,
    'name' : IDL.Text,
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
    'enteredBy' : IDL.Text,
  });
  const PlotEntry = IDL.Record({
    'dateActivated' : Time,
    'department' : IDL.Text,
    'plotName' : IDL.Text,
  });
  const MonthlyGoal = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'plotEntries' : IDL.Vec(PlotEntry),
    'actualPlots' : IDL.Nat,
    'year' : IDL.Nat,
    'targetPlots' : IDL.Nat,
  });
  const WeeklyReport = IDL.Record({
    'departmentLead' : IDL.Text,
    'departmentName' : IDL.Text,
    'planForNextWeek' : IDL.Text,
    'achievements' : IDL.Text,
    'weekEnding' : Time,
    'challenges' : IDL.Text,
  });
  const WorkerDailyRecord = IDL.Record({
    'workerId' : IDL.Nat,
    'arrivalTime' : IDL.Opt(Time),
    'present' : IDL.Bool,
    'departureTime' : IDL.Opt(Time),
    'date' : Time,
    'timeOnFarm' : IDL.Opt(IDL.Int),
    'enteredBy' : IDL.Text,
  });
  const Worker = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'enteredBy' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addExpense' : IDL.Func(
        [IDL.Float64, Time, ExpenseType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addFarmTimeEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [FarmTimeEntry],
        [],
      ),
    'addHarvestEntry' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [HarvestEntry],
        [],
      ),
    'addIncome' : IDL.Func(
        [IDL.Float64, Time, IncomeSource, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addInventoryItem' : IDL.Func(
        [IDL.Text, ItemType, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addMonthlyGoal' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'addPlotEntry' : IDL.Func([IDL.Nat, IDL.Text, Time, IDL.Text], [], []),
    'addSale' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addWorker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'approveUser' : IDL.Func([IDL.Principal], [], []),
    'bootstrapAdminRegistration' : IDL.Func([], [], []),
    'deleteAttachment' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteFarmTimeEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteFileAttachment' : IDL.Func([IDL.Nat], [], []),
    'deleteHarvestEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteIncome' : IDL.Func([IDL.Nat], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteSale' : IDL.Func([IDL.Nat], [], []),
    'deleteWorker' : IDL.Func([IDL.Nat], [], []),
    'getAttachment' : IDL.Func([IDL.Nat], [IDL.Opt(FileAttachment)], ['query']),
    'getAttachmentsForItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FileAttachmentMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCustomerPurchaseHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Sale)],
        ['query'],
      ),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
    'getFarmTimeEntries' : IDL.Func([], [IDL.Vec(FarmTimeEntry)], ['query']),
    'getFarmTimeEntriesByWorker' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FarmTimeEntry)],
        ['query'],
      ),
    'getFileAttachment' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(FileAttachment)],
        ['query'],
      ),
    'getFileAttachmentMetadata' : IDL.Func(
        [],
        [IDL.Vec(FileAttachmentMetadata)],
        ['query'],
      ),
    'getHarvestEntries' : IDL.Func([], [IDL.Vec(HarvestEntry)], ['query']),
    'getIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getMonthlyGoal' : IDL.Func([IDL.Nat], [IDL.Opt(MonthlyGoal)], ['query']),
    'getMonthlyGoals' : IDL.Func([], [IDL.Vec(MonthlyGoal)], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyReports' : IDL.Func([], [IDL.Vec(WeeklyReport)], ['query']),
    'getWeeklyReportsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(WeeklyReport)],
        ['query'],
      ),
    'getWeeklyReportsByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WeeklyReport)],
        ['query'],
      ),
    'getWorkerDailyRecords' : IDL.Func(
        [],
        [IDL.Vec(WorkerDailyRecord)],
        ['query'],
      ),
    'getWorkerDailyRecordsByWorker' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WorkerDailyRecord)],
        ['query'],
      ),
    'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'initializeFixedMonthlyGoals' : IDL.Func([], [], []),
    'isAutoRegisteredAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listPendingUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'recordWorkerDay' : IDL.Func(
        [IDL.Nat, Time, IDL.Bool, IDL.Opt(Time), IDL.Opt(Time)],
        [],
        [],
      ),
    'rejectUser' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitWeeklyReport' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Float64, Time, ExpenseType, IDL.Text],
        [],
        [],
      ),
    'updateFarmTimeEntry' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Opt(FarmTimeEntry)],
        [],
      ),
    'updateHarvestEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(HarvestEntry)],
        [],
      ),
    'updateIncome' : IDL.Func(
        [IDL.Nat, IDL.Float64, Time, IncomeSource, IDL.Text],
        [],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, ItemType, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'updateWorker' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'uploadAttachmentToItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Nat],
        [],
      ),
    'uploadFileAttachment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };