/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ExpenseType = IDL.Variant({
  'fertilizers' : IDL.Null,
  'transportation' : IDL.Null,
  'other' : IDL.Null,
  'equipment' : IDL.Null,
  'labor' : IDL.Null,
  'packaging' : IDL.Null,
});
export const IncomeSource = IDL.Variant({
  'other' : IDL.Null,
  'local' : IDL.Null,
  'market' : IDL.Null,
  'wholesale' : IDL.Null,
});
export const ItemType = IDL.Variant({
  'equipment' : IDL.Null,
  'peppers' : IDL.Null,
  'fertilizer' : IDL.Null,
  'pesticide' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'onLeave' : IDL.Null,
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  }),
  'workerId' : IDL.Nat,
  'date' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'inventoryItemId' : IDL.Nat,
  'date' : Time,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'customerType' : IDL.Text,
  'name' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const ExpenseRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'category' : ExpenseType,
  'amount' : IDL.Float64,
});
export const IncomeRecord = IDL.Record({
  'id' : IDL.Nat,
  'source' : IncomeSource,
  'date' : Time,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'costPerUnit' : IDL.Float64,
  'name' : IDL.Text,
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
});
export const Worker = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addExpense' : IDL.Func(
      [IDL.Float64, Time, ExpenseType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addIncome' : IDL.Func(
      [IDL.Float64, Time, IncomeSource, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addInventoryItem' : IDL.Func(
      [IDL.Text, ItemType, IDL.Nat, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addSale' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64], [IDL.Nat], []),
  'addWorker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAttendanceRecords' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerPurchaseHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Sale)],
      ['query'],
    ),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
  'getIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerAttendance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [
        IDL.Nat,
        Time,
        IDL.Variant({
          'onLeave' : IDL.Null,
          'present' : IDL.Null,
          'late' : IDL.Null,
          'absent' : IDL.Null,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInventoryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, ItemType, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ExpenseType = IDL.Variant({
    'fertilizers' : IDL.Null,
    'transportation' : IDL.Null,
    'other' : IDL.Null,
    'equipment' : IDL.Null,
    'labor' : IDL.Null,
    'packaging' : IDL.Null,
  });
  const IncomeSource = IDL.Variant({
    'other' : IDL.Null,
    'local' : IDL.Null,
    'market' : IDL.Null,
    'wholesale' : IDL.Null,
  });
  const ItemType = IDL.Variant({
    'equipment' : IDL.Null,
    'peppers' : IDL.Null,
    'fertilizer' : IDL.Null,
    'pesticide' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'onLeave' : IDL.Null,
      'present' : IDL.Null,
      'late' : IDL.Null,
      'absent' : IDL.Null,
    }),
    'workerId' : IDL.Nat,
    'date' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'inventoryItemId' : IDL.Nat,
    'date' : Time,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'customerType' : IDL.Text,
    'name' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const ExpenseRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'category' : ExpenseType,
    'amount' : IDL.Float64,
  });
  const IncomeRecord = IDL.Record({
    'id' : IDL.Nat,
    'source' : IncomeSource,
    'date' : Time,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'costPerUnit' : IDL.Float64,
    'name' : IDL.Text,
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
  });
  const Worker = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addExpense' : IDL.Func(
        [IDL.Float64, Time, ExpenseType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addIncome' : IDL.Func(
        [IDL.Float64, Time, IncomeSource, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addInventoryItem' : IDL.Func(
        [IDL.Text, ItemType, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addSale' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addWorker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerPurchaseHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Sale)],
        ['query'],
      ),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
    'getIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerAttendance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [
          IDL.Nat,
          Time,
          IDL.Variant({
            'onLeave' : IDL.Null,
            'present' : IDL.Null,
            'late' : IDL.Null,
            'absent' : IDL.Null,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInventoryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, ItemType, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };