/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ExpenseRecord {
    id: bigint;
    date: Time;
    description: string;
    category: ExpenseType;
    amount: number;
    enteredBy: string;
}
export interface Sale {
    id: bigint;
    inventoryItemId: bigint;
    date: Time;
    quantity: bigint;
    customerId: bigint;
    unitPrice: number;
    enteredBy: string;
}
export interface Customer {
    id: bigint;
    customerType: string;
    name: string;
    enteredBy: string;
    contactDetails: string;
}
export interface InventoryItem {
    id: bigint;
    costPerUnit: number;
    name: string;
    itemType: ItemType;
    quantity: bigint;
    enteredBy: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface IncomeRecord {
    id: bigint;
    source: IncomeSource;
    date: Time;
    description: string;
    amount: number;
    enteredBy: string;
}
export interface Worker {
    id: bigint;
    name: string;
    role: string;
    enteredBy: string;
}
export interface UserProfile {
    name: string;
}
export interface WorkerDailyRecord {
    workerId: bigint;
    arrivalTime?: Time;
    present: boolean;
    departureTime?: Time;
    date: Time;
    timeOnFarm?: bigint;
    enteredBy: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ExpenseType {
    fertilizers = "fertilizers",
    transportation = "transportation",
    other = "other",
    equipment = "equipment",
    labor = "labor",
    packaging = "packaging"
}
export enum IncomeSource {
    other = "other",
    local = "local",
    market = "market",
    wholesale = "wholesale"
}
export enum ItemType {
    equipment = "equipment",
    peppers = "peppers",
    fertilizer = "fertilizer",
    pesticide = "pesticide"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomer(name: string, contactDetails: string, customerType: string): Promise<bigint>;
    addExpense(amount: number, date: Time, category: ExpenseType, description: string): Promise<bigint>;
    addIncome(amount: number, date: Time, source: IncomeSource, description: string): Promise<bigint>;
    addInventoryItem(name: string, itemType: ItemType, quantity: bigint, costPerUnit: number): Promise<bigint>;
    addSale(customerId: bigint, inventoryItemId: bigint, quantity: bigint, unitPrice: number): Promise<bigint>;
    addWorker(name: string, role: string): Promise<bigint>;
    approveUser(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bootstrapAdminRegistration(): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerPurchaseHistory(customerId: bigint): Promise<Array<Sale>>;
    getCustomers(): Promise<Array<Customer>>;
    getExpenseRecords(): Promise<Array<ExpenseRecord>>;
    getIncomeRecords(): Promise<Array<IncomeRecord>>;
    getInventoryItems(): Promise<Array<InventoryItem>>;
    getSales(): Promise<Array<Sale>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkerDailyRecords(): Promise<Array<WorkerDailyRecord>>;
    getWorkerDailyRecordsByWorker(workerId: bigint): Promise<Array<WorkerDailyRecord>>;
    getWorkers(): Promise<Array<Worker>>;
    isAutoRegisteredAdmin(principal: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listPendingUsers(): Promise<Array<UserProfile>>;
    recordWorkerDay(workerId: bigint, date: Time, present: boolean, arrivalTime: Time | null, departureTime: Time | null): Promise<void>;
    rejectUser(user: Principal): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateExpense(id: bigint, amount: number, date: Time, category: ExpenseType, description: string): Promise<void>;
    updateInventoryItem(id: bigint, name: string, itemType: ItemType, quantity: bigint, costPerUnit: number): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, ExpenseRecord as _ExpenseRecord, ExpenseType as _ExpenseType, IncomeRecord as _IncomeRecord, IncomeSource as _IncomeSource, InventoryItem as _InventoryItem, ItemType as _ItemType, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, WorkerDailyRecord as _WorkerDailyRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomer(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async addExpense(arg0: number, arg1: Time, arg2: ExpenseType, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, to_candid_ExpenseType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, to_candid_ExpenseType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addIncome(arg0: number, arg1: Time, arg2: IncomeSource, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncome(arg0, arg1, to_candid_IncomeSource_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncome(arg0, arg1, to_candid_IncomeSource_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addInventoryItem(arg0: string, arg1: ItemType, arg2: bigint, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0, to_candid_ItemType_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0, to_candid_ItemType_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addSale(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addWorker(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorker(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorker(arg0, arg1);
            return result;
        }
    }
    async approveUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bootstrapAdminRegistration(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapAdminRegistration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapAdminRegistration();
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerPurchaseHistory(arg0: bigint): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerPurchaseHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerPurchaseHistory(arg0);
            return result;
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getExpenseRecords(): Promise<Array<ExpenseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseRecords();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseRecords();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomeRecords(): Promise<Array<IncomeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeRecords();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeRecords();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItems();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItems();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerDailyRecords(): Promise<Array<WorkerDailyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerDailyRecords();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerDailyRecords();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerDailyRecordsByWorker(arg0: bigint): Promise<Array<WorkerDailyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerDailyRecordsByWorker(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerDailyRecordsByWorker(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkers(): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkers();
            return result;
        }
    }
    async isAutoRegisteredAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAutoRegisteredAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAutoRegisteredAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingUsers();
            return result;
        }
    }
    async recordWorkerDay(arg0: bigint, arg1: Time, arg2: boolean, arg3: Time | null, arg4: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWorkerDay(arg0, arg1, arg2, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWorkerDay(arg0, arg1, arg2, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async rejectUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectUser(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: number, arg2: Time, arg3: ExpenseType, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, arg2, to_candid_ExpenseType_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, arg2, to_candid_ExpenseType_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateInventoryItem(arg0: bigint, arg1: string, arg2: ItemType, arg3: bigint, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, arg1, to_candid_ItemType_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, arg1, to_candid_ItemType_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseRecord_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseRecord): ExpenseRecord {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseType): ExpenseType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_IncomeRecord_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeRecord): IncomeRecord {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_IncomeSource_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeSource): IncomeSource {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerDailyRecord_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerDailyRecord): WorkerDailyRecord {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    description: string;
    category: _ExpenseType;
    amount: number;
    enteredBy: string;
}): {
    id: bigint;
    date: Time;
    description: string;
    category: ExpenseType;
    amount: number;
    enteredBy: string;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        category: from_candid_ExpenseType_n15(_uploadFile, _downloadFile, value.category),
        amount: value.amount,
        enteredBy: value.enteredBy
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    source: _IncomeSource;
    date: _Time;
    description: string;
    amount: number;
    enteredBy: string;
}): {
    id: bigint;
    source: IncomeSource;
    date: Time;
    description: string;
    amount: number;
    enteredBy: string;
} {
    return {
        id: value.id,
        source: from_candid_IncomeSource_n20(_uploadFile, _downloadFile, value.source),
        date: value.date,
        description: value.description,
        amount: value.amount,
        enteredBy: value.enteredBy
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    costPerUnit: number;
    name: string;
    itemType: _ItemType;
    quantity: bigint;
    enteredBy: string;
}): {
    id: bigint;
    costPerUnit: number;
    name: string;
    itemType: ItemType;
    quantity: bigint;
    enteredBy: string;
} {
    return {
        id: value.id,
        costPerUnit: value.costPerUnit,
        name: value.name,
        itemType: from_candid_ItemType_n25(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity,
        enteredBy: value.enteredBy
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workerId: bigint;
    arrivalTime: [] | [_Time];
    present: boolean;
    departureTime: [] | [_Time];
    date: _Time;
    timeOnFarm: [] | [bigint];
    enteredBy: string;
}): {
    workerId: bigint;
    arrivalTime?: Time;
    present: boolean;
    departureTime?: Time;
    date: Time;
    timeOnFarm?: bigint;
    enteredBy: string;
} {
    return {
        workerId: value.workerId,
        arrivalTime: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.arrivalTime)),
        present: value.present,
        departureTime: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.departureTime)),
        date: value.date,
        timeOnFarm: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.timeOnFarm)),
        enteredBy: value.enteredBy
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n35(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fertilizers: null;
} | {
    transportation: null;
} | {
    other: null;
} | {
    equipment: null;
} | {
    labor: null;
} | {
    packaging: null;
}): ExpenseType {
    return "fertilizers" in value ? ExpenseType.fertilizers : "transportation" in value ? ExpenseType.transportation : "other" in value ? ExpenseType.other : "equipment" in value ? ExpenseType.equipment : "labor" in value ? ExpenseType.labor : "packaging" in value ? ExpenseType.packaging : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    local: null;
} | {
    market: null;
} | {
    wholesale: null;
}): IncomeSource {
    return "other" in value ? IncomeSource.other : "local" in value ? IncomeSource.local : "market" in value ? IncomeSource.market : "wholesale" in value ? IncomeSource.wholesale : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    equipment: null;
} | {
    peppers: null;
} | {
    fertilizer: null;
} | {
    pesticide: null;
}): ItemType {
    return "equipment" in value ? ItemType.equipment : "peppers" in value ? ItemType.peppers : "fertilizer" in value ? ItemType.fertilizer : "pesticide" in value ? ItemType.pesticide : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExpenseRecord>): Array<ExpenseRecord> {
    return value.map((x)=>from_candid_ExpenseRecord_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncomeRecord>): Array<IncomeRecord> {
    return value.map((x)=>from_candid_IncomeRecord_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerDailyRecord>): Array<WorkerDailyRecord> {
    return value.map((x)=>from_candid_WorkerDailyRecord_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n33(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseType): _ExpenseType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_IncomeSource_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncomeSource): _IncomeSource {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ItemType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseType): {
    fertilizers: null;
} | {
    transportation: null;
} | {
    other: null;
} | {
    equipment: null;
} | {
    labor: null;
} | {
    packaging: null;
} {
    return value == ExpenseType.fertilizers ? {
        fertilizers: null
    } : value == ExpenseType.transportation ? {
        transportation: null
    } : value == ExpenseType.other ? {
        other: null
    } : value == ExpenseType.equipment ? {
        equipment: null
    } : value == ExpenseType.labor ? {
        labor: null
    } : value == ExpenseType.packaging ? {
        packaging: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncomeSource): {
    other: null;
} | {
    local: null;
} | {
    market: null;
} | {
    wholesale: null;
} {
    return value == IncomeSource.other ? {
        other: null
    } : value == IncomeSource.local ? {
        local: null
    } : value == IncomeSource.market ? {
        market: null
    } : value == IncomeSource.wholesale ? {
        wholesale: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    equipment: null;
} | {
    peppers: null;
} | {
    fertilizer: null;
} | {
    pesticide: null;
} {
    return value == ItemType.equipment ? {
        equipment: null
    } : value == ItemType.peppers ? {
        peppers: null
    } : value == ItemType.fertilizer ? {
        fertilizer: null
    } : value == ItemType.pesticide ? {
        pesticide: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
