/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Customer {
  'id' : bigint,
  'customerType' : string,
  'name' : string,
  'contactDetails' : string,
}
export interface ExpenseRecord {
  'id' : bigint,
  'date' : Time,
  'description' : string,
  'category' : ExpenseType,
  'amount' : number,
}
export type ExpenseType = { 'fertilizers' : null } |
  { 'transportation' : null } |
  { 'other' : null } |
  { 'equipment' : null } |
  { 'labor' : null } |
  { 'packaging' : null };
export interface IncomeRecord {
  'id' : bigint,
  'source' : IncomeSource,
  'date' : Time,
  'description' : string,
  'amount' : number,
}
export type IncomeSource = { 'other' : null } |
  { 'local' : null } |
  { 'market' : null } |
  { 'wholesale' : null };
export interface InventoryItem {
  'id' : bigint,
  'costPerUnit' : number,
  'name' : string,
  'itemType' : ItemType,
  'quantity' : bigint,
}
export type ItemType = { 'equipment' : null } |
  { 'peppers' : null } |
  { 'fertilizer' : null } |
  { 'pesticide' : null };
export interface Sale {
  'id' : bigint,
  'inventoryItemId' : bigint,
  'date' : Time,
  'quantity' : bigint,
  'customerId' : bigint,
  'unitPrice' : number,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worker { 'id' : bigint, 'name' : string, 'role' : string }
export interface WorkerDailyRecord {
  'workerId' : bigint,
  'arrivalTime' : [] | [Time],
  'present' : boolean,
  'departureTime' : [] | [Time],
  'date' : Time,
  'timeOnFarm' : [] | [bigint],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[string, string, string], bigint>,
  'addExpense' : ActorMethod<[number, Time, ExpenseType, string], bigint>,
  'addIncome' : ActorMethod<[number, Time, IncomeSource, string], bigint>,
  'addInventoryItem' : ActorMethod<[string, ItemType, bigint, number], bigint>,
  'addSale' : ActorMethod<[bigint, bigint, bigint, number], bigint>,
  'addWorker' : ActorMethod<[string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdminRegistration' : ActorMethod<[], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerPurchaseHistory' : ActorMethod<[bigint], Array<Sale>>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getExpenseRecords' : ActorMethod<[], Array<ExpenseRecord>>,
  'getIncomeRecords' : ActorMethod<[], Array<IncomeRecord>>,
  'getInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerDailyRecords' : ActorMethod<[], Array<WorkerDailyRecord>>,
  'getWorkerDailyRecordsByWorker' : ActorMethod<
    [bigint],
    Array<WorkerDailyRecord>
  >,
  'getWorkers' : ActorMethod<[], Array<Worker>>,
  'isAutoRegisteredAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'recordWorkerDay' : ActorMethod<
    [bigint, Time, boolean, [] | [Time], [] | [Time]],
    undefined
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateExpense' : ActorMethod<
    [bigint, number, Time, ExpenseType, string],
    undefined
  >,
  'updateInventoryItem' : ActorMethod<
    [bigint, string, ItemType, bigint, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];