/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ExpenseType = IDL.Variant({
  'fertilizers' : IDL.Null,
  'transportation' : IDL.Null,
  'other' : IDL.Null,
  'equipment' : IDL.Null,
  'labor' : IDL.Null,
  'packaging' : IDL.Null,
});
export const IncomeSource = IDL.Variant({
  'other' : IDL.Null,
  'local' : IDL.Null,
  'market' : IDL.Null,
  'wholesale' : IDL.Null,
});
export const ItemType = IDL.Variant({
  'equipment' : IDL.Null,
  'peppers' : IDL.Null,
  'fertilizer' : IDL.Null,
  'pesticide' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'inventoryItemId' : IDL.Nat,
  'date' : Time,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'enteredBy' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'customerType' : IDL.Text,
  'name' : IDL.Text,
  'enteredBy' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const ExpenseRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'category' : ExpenseType,
  'amount' : IDL.Float64,
  'enteredBy' : IDL.Text,
});
export const IncomeRecord = IDL.Record({
  'id' : IDL.Nat,
  'source' : IncomeSource,
  'date' : Time,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
  'enteredBy' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'costPerUnit' : IDL.Float64,
  'name' : IDL.Text,
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
  'enteredBy' : IDL.Text,
});
export const WorkerDailyRecord = IDL.Record({
  'workerId' : IDL.Nat,
  'arrivalTime' : IDL.Opt(Time),
  'present' : IDL.Bool,
  'departureTime' : IDL.Opt(Time),
  'date' : Time,
  'timeOnFarm' : IDL.Opt(IDL.Int),
  'enteredBy' : IDL.Text,
});
export const Worker = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'enteredBy' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addExpense' : IDL.Func(
      [IDL.Float64, Time, ExpenseType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addIncome' : IDL.Func(
      [IDL.Float64, Time, IncomeSource, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addInventoryItem' : IDL.Func(
      [IDL.Text, ItemType, IDL.Nat, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addSale' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64], [IDL.Nat], []),
  'addWorker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'approveUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapAdminRegistration' : IDL.Func([], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerPurchaseHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Sale)],
      ['query'],
    ),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
  'getIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerDailyRecords' : IDL.Func(
      [],
      [IDL.Vec(WorkerDailyRecord)],
      ['query'],
    ),
  'getWorkerDailyRecordsByWorker' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WorkerDailyRecord)],
      ['query'],
    ),
  'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'isAutoRegisteredAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listPendingUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'recordWorkerDay' : IDL.Func(
      [IDL.Nat, Time, IDL.Bool, IDL.Opt(Time), IDL.Opt(Time)],
      [],
      [],
    ),
  'rejectUser' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Float64, Time, ExpenseType, IDL.Text],
      [],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, ItemType, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ExpenseType = IDL.Variant({
    'fertilizers' : IDL.Null,
    'transportation' : IDL.Null,
    'other' : IDL.Null,
    'equipment' : IDL.Null,
    'labor' : IDL.Null,
    'packaging' : IDL.Null,
  });
  const IncomeSource = IDL.Variant({
    'other' : IDL.Null,
    'local' : IDL.Null,
    'market' : IDL.Null,
    'wholesale' : IDL.Null,
  });
  const ItemType = IDL.Variant({
    'equipment' : IDL.Null,
    'peppers' : IDL.Null,
    'fertilizer' : IDL.Null,
    'pesticide' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'inventoryItemId' : IDL.Nat,
    'date' : Time,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'enteredBy' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'customerType' : IDL.Text,
    'name' : IDL.Text,
    'enteredBy' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const ExpenseRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'category' : ExpenseType,
    'amount' : IDL.Float64,
    'enteredBy' : IDL.Text,
  });
  const IncomeRecord = IDL.Record({
    'id' : IDL.Nat,
    'source' : IncomeSource,
    'date' : Time,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
    'enteredBy' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'costPerUnit' : IDL.Float64,
    'name' : IDL.Text,
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
    'enteredBy' : IDL.Text,
  });
  const WorkerDailyRecord = IDL.Record({
    'workerId' : IDL.Nat,
    'arrivalTime' : IDL.Opt(Time),
    'present' : IDL.Bool,
    'departureTime' : IDL.Opt(Time),
    'date' : Time,
    'timeOnFarm' : IDL.Opt(IDL.Int),
    'enteredBy' : IDL.Text,
  });
  const Worker = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'enteredBy' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addExpense' : IDL.Func(
        [IDL.Float64, Time, ExpenseType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addIncome' : IDL.Func(
        [IDL.Float64, Time, IncomeSource, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addInventoryItem' : IDL.Func(
        [IDL.Text, ItemType, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addSale' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addWorker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'approveUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapAdminRegistration' : IDL.Func([], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerPurchaseHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Sale)],
        ['query'],
      ),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getExpenseRecords' : IDL.Func([], [IDL.Vec(ExpenseRecord)], ['query']),
    'getIncomeRecords' : IDL.Func([], [IDL.Vec(IncomeRecord)], ['query']),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerDailyRecords' : IDL.Func(
        [],
        [IDL.Vec(WorkerDailyRecord)],
        ['query'],
      ),
    'getWorkerDailyRecordsByWorker' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WorkerDailyRecord)],
        ['query'],
      ),
    'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'isAutoRegisteredAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listPendingUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'recordWorkerDay' : IDL.Func(
        [IDL.Nat, Time, IDL.Bool, IDL.Opt(Time), IDL.Opt(Time)],
        [],
        [],
      ),
    'rejectUser' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Float64, Time, ExpenseType, IDL.Text],
        [],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, ItemType, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };