/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlotEntry {
    dateActivated: Time;
    department: string;
    plotName: string;
}
export type Time = bigint;
export interface ExpenseRecord {
    id: bigint;
    date: Time;
    description: string;
    category: ExpenseType;
    amount: number;
    enteredBy: string;
}
export interface WeeklyReport {
    departmentLead: string;
    departmentName: string;
    planForNextWeek: string;
    achievements: string;
    weekEnding: Time;
    challenges: string;
}
export interface Sale {
    id: bigint;
    inventoryItemId: bigint;
    date: Time;
    quantity: bigint;
    customerId: bigint;
    unitPrice: number;
    enteredBy: string;
}
export interface Customer {
    id: bigint;
    customerType: string;
    name: string;
    enteredBy: string;
    contactDetails: string;
}
export interface InventoryItem {
    id: bigint;
    costPerUnit: number;
    name: string;
    itemType: ItemType;
    quantity: bigint;
    enteredBy: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface MonthlyGoal {
    id: bigint;
    month: bigint;
    plotEntries: Array<PlotEntry>;
    actualPlots: bigint;
    year: bigint;
    targetPlots: bigint;
}
export interface IncomeRecord {
    id: bigint;
    source: IncomeSource;
    date: Time;
    description: string;
    amount: number;
    enteredBy: string;
}
export interface FileAttachment {
    id: bigint;
    content: Uint8Array;
    inventoryItemId: bigint;
    mimeType: string;
    filename: string;
}
export interface FarmTimeEntry {
    id: bigint;
    status: string;
    workerId: bigint;
    arrivalTime?: string;
    departureTime?: string;
    date: string;
    hoursOnFarm?: number;
    timestamp: bigint;
    workerName: string;
    enteredBy: Principal;
}
export interface Department {
    leadName: string;
    name: string;
    description: string;
}
export interface HarvestEntry {
    id: bigint;
    date: string;
    notes: string;
    timestamp: bigint;
    plotLocation: string;
    enteredBy: Principal;
    harvestedBy: string;
    quantityKg: number;
}
export interface FileAttachmentMetadata {
    id: bigint;
    inventoryItemId: bigint;
    mimeType: string;
    filename: string;
}
export interface Worker {
    id: bigint;
    name: string;
    role: string;
    enteredBy: string;
}
export interface UserProfile {
    name: string;
}
export interface WorkerDailyRecord {
    workerId: bigint;
    arrivalTime?: Time;
    present: boolean;
    departureTime?: Time;
    date: Time;
    timeOnFarm?: bigint;
    enteredBy: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ExpenseType {
    fertilizers = "fertilizers",
    transportation = "transportation",
    other = "other",
    equipment = "equipment",
    labor = "labor",
    packaging = "packaging"
}
export enum IncomeSource {
    other = "other",
    local = "local",
    market = "market",
    wholesale = "wholesale"
}
export enum ItemType {
    equipment = "equipment",
    peppers = "peppers",
    fertilizer = "fertilizer",
    pesticide = "pesticide"
}
export interface backendInterface {
    addCustomer(name: string, contactDetails: string, customerType: string): Promise<bigint>;
    addExpense(amount: number, date: Time, category: ExpenseType, description: string): Promise<bigint>;
    addFarmTimeEntry(workerId: bigint, workerName: string, date: string, arrivalTime: string | null, departureTime: string | null, status: string): Promise<FarmTimeEntry>;
    addHarvestEntry(date: string, quantityKg: number, harvestedBy: string, plotLocation: string, notes: string): Promise<HarvestEntry>;
    addIncome(amount: number, date: Time, source: IncomeSource, description: string): Promise<bigint>;
    addInventoryItem(name: string, itemType: ItemType, quantity: bigint, costPerUnit: number): Promise<bigint>;
    addMonthlyGoal(year: bigint, month: bigint, targetPlots: bigint): Promise<bigint>;
    addPlotEntry(monthlyGoalId: bigint, plotName: string, dateActivated: Time, department: string): Promise<void>;
    addSale(customerId: bigint, inventoryItemId: bigint, quantity: bigint, unitPrice: number): Promise<bigint>;
    addWorker(name: string, role: string): Promise<bigint>;
    approveUser(user: Principal): Promise<void>;
    bootstrapAdminRegistration(): Promise<void>;
    deleteAttachment(id: bigint): Promise<void>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    deleteFarmTimeEntry(id: bigint): Promise<boolean>;
    deleteFileAttachment(id: bigint): Promise<void>;
    deleteHarvestEntry(id: bigint): Promise<boolean>;
    deleteIncome(id: bigint): Promise<void>;
    deleteInventoryItem(id: bigint): Promise<void>;
    deleteSale(id: bigint): Promise<void>;
    deleteWorker(id: bigint): Promise<void>;
    getAttachment(id: bigint): Promise<FileAttachment | null>;
    getAttachmentsForItem(inventoryItemId: bigint): Promise<Array<FileAttachmentMetadata>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCustomerPurchaseHistory(customerId: bigint): Promise<Array<Sale>>;
    getCustomers(): Promise<Array<Customer>>;
    getDepartments(): Promise<Array<Department>>;
    getExpenseRecords(): Promise<Array<ExpenseRecord>>;
    getFarmTimeEntries(): Promise<Array<FarmTimeEntry>>;
    getFarmTimeEntriesByWorker(workerId: bigint): Promise<Array<FarmTimeEntry>>;
    getFileAttachment(id: bigint): Promise<FileAttachment | null>;
    getFileAttachmentMetadata(): Promise<Array<FileAttachmentMetadata>>;
    getHarvestEntries(): Promise<Array<HarvestEntry>>;
    getIncomeRecords(): Promise<Array<IncomeRecord>>;
    getInventoryItems(): Promise<Array<InventoryItem>>;
    getMonthlyGoal(id: bigint): Promise<MonthlyGoal | null>;
    getMonthlyGoals(): Promise<Array<MonthlyGoal>>;
    getSales(): Promise<Array<Sale>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeeklyReports(): Promise<Array<WeeklyReport>>;
    getWeeklyReportsByDateRange(startDate: Time, endDate: Time): Promise<Array<WeeklyReport>>;
    getWeeklyReportsByDepartment(departmentName: string): Promise<Array<WeeklyReport>>;
    getWorkerDailyRecords(): Promise<Array<WorkerDailyRecord>>;
    getWorkerDailyRecordsByWorker(workerId: bigint): Promise<Array<WorkerDailyRecord>>;
    getWorkers(): Promise<Array<Worker>>;
    initializeFixedMonthlyGoals(): Promise<void>;
    isAutoRegisteredAdmin(principal: Principal): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listPendingUsers(): Promise<Array<UserProfile>>;
    recordWorkerDay(workerId: bigint, date: Time, present: boolean, arrivalTime: Time | null, departureTime: Time | null): Promise<void>;
    rejectUser(user: Principal): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    submitWeeklyReport(departmentLead: string, departmentName: string, weekEnding: Time, achievements: string, challenges: string, planForNextWeek: string): Promise<void>;
    updateCustomer(id: bigint, name: string, contactDetails: string, customerType: string): Promise<void>;
    updateExpense(id: bigint, amount: number, date: Time, category: ExpenseType, description: string): Promise<void>;
    updateFarmTimeEntry(id: bigint, arrivalTime: string | null, departureTime: string | null, status: string): Promise<FarmTimeEntry | null>;
    updateHarvestEntry(id: bigint, date: string, quantityKg: number, harvestedBy: string, plotLocation: string, notes: string): Promise<HarvestEntry | null>;
    updateIncome(id: bigint, amount: number, date: Time, source: IncomeSource, description: string): Promise<void>;
    updateInventoryItem(id: bigint, name: string, itemType: ItemType, quantity: bigint, costPerUnit: number): Promise<void>;
    updateWorker(id: bigint, name: string, role: string): Promise<void>;
    uploadAttachmentToItem(inventoryItemId: bigint, filename: string, mimeType: string, content: Uint8Array): Promise<bigint>;
    uploadFileAttachment(filename: string, mimeType: string, content: Uint8Array): Promise<bigint>;
}
import type { ApprovalStatus as _ApprovalStatus, ExpenseRecord as _ExpenseRecord, ExpenseType as _ExpenseType, FarmTimeEntry as _FarmTimeEntry, FileAttachment as _FileAttachment, HarvestEntry as _HarvestEntry, IncomeRecord as _IncomeRecord, IncomeSource as _IncomeSource, InventoryItem as _InventoryItem, ItemType as _ItemType, MonthlyGoal as _MonthlyGoal, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, WorkerDailyRecord as _WorkerDailyRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async addExpense(arg0: number, arg1: Time, arg2: ExpenseType, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, to_candid_ExpenseType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, to_candid_ExpenseType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addFarmTimeEntry(arg0: bigint, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: string): Promise<FarmTimeEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addFarmTimeEntry(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_FarmTimeEntry_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFarmTimeEntry(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_FarmTimeEntry_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async addHarvestEntry(arg0: string, arg1: number, arg2: string, arg3: string, arg4: string): Promise<HarvestEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addHarvestEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHarvestEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addIncome(arg0: number, arg1: Time, arg2: IncomeSource, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncome(arg0, arg1, to_candid_IncomeSource_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncome(arg0, arg1, to_candid_IncomeSource_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addInventoryItem(arg0: string, arg1: ItemType, arg2: bigint, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0, to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0, to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addMonthlyGoal(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMonthlyGoal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMonthlyGoal(arg0, arg1, arg2);
            return result;
        }
    }
    async addPlotEntry(arg0: bigint, arg1: string, arg2: Time, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlotEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlotEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addSale(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addWorker(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorker(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorker(arg0, arg1);
            return result;
        }
    }
    async approveUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0);
            return result;
        }
    }
    async bootstrapAdminRegistration(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapAdminRegistration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapAdminRegistration();
            return result;
        }
    }
    async deleteAttachment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAttachment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAttachment(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteFarmTimeEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFarmTimeEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFarmTimeEntry(arg0);
            return result;
        }
    }
    async deleteFileAttachment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFileAttachment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFileAttachment(arg0);
            return result;
        }
    }
    async deleteHarvestEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHarvestEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHarvestEntry(arg0);
            return result;
        }
    }
    async deleteIncome(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncome(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteSale(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSale(arg0);
            return result;
        }
    }
    async deleteWorker(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorker(arg0);
            return result;
        }
    }
    async getAttachment(arg0: bigint): Promise<FileAttachment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttachment(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttachment(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttachmentsForItem(arg0: bigint): Promise<Array<FileAttachmentMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttachmentsForItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttachmentsForItem(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerPurchaseHistory(arg0: bigint): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerPurchaseHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerPurchaseHistory(arg0);
            return result;
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getDepartments(): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartments();
            return result;
        }
    }
    async getExpenseRecords(): Promise<Array<ExpenseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseRecords();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseRecords();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmTimeEntries(): Promise<Array<FarmTimeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmTimeEntries();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmTimeEntries();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmTimeEntriesByWorker(arg0: bigint): Promise<Array<FarmTimeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmTimeEntriesByWorker(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmTimeEntriesByWorker(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileAttachment(arg0: bigint): Promise<FileAttachment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileAttachment(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileAttachment(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileAttachmentMetadata(): Promise<Array<FileAttachmentMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileAttachmentMetadata();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileAttachmentMetadata();
            return result;
        }
    }
    async getHarvestEntries(): Promise<Array<HarvestEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHarvestEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHarvestEntries();
            return result;
        }
    }
    async getIncomeRecords(): Promise<Array<IncomeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeRecords();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeRecords();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItems();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItems();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyGoal(arg0: bigint): Promise<MonthlyGoal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyGoal(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyGoal(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyGoals(): Promise<Array<MonthlyGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyGoals();
            return result;
        }
    }
    async getSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyReports(): Promise<Array<WeeklyReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyReports();
            return result;
        }
    }
    async getWeeklyReportsByDateRange(arg0: Time, arg1: Time): Promise<Array<WeeklyReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyReportsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyReportsByDateRange(arg0, arg1);
            return result;
        }
    }
    async getWeeklyReportsByDepartment(arg0: string): Promise<Array<WeeklyReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyReportsByDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyReportsByDepartment(arg0);
            return result;
        }
    }
    async getWorkerDailyRecords(): Promise<Array<WorkerDailyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerDailyRecords();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerDailyRecords();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerDailyRecordsByWorker(arg0: bigint): Promise<Array<WorkerDailyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerDailyRecordsByWorker(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerDailyRecordsByWorker(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkers(): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkers();
            return result;
        }
    }
    async initializeFixedMonthlyGoals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeFixedMonthlyGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeFixedMonthlyGoals();
            return result;
        }
    }
    async isAutoRegisteredAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAutoRegisteredAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAutoRegisteredAdmin(arg0);
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingUsers();
            return result;
        }
    }
    async recordWorkerDay(arg0: bigint, arg1: Time, arg2: boolean, arg3: Time | null, arg4: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWorkerDay(arg0, arg1, arg2, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWorkerDay(arg0, arg1, arg2, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async rejectUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectUser(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitWeeklyReport(arg0: string, arg1: string, arg2: Time, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWeeklyReport(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWeeklyReport(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateCustomer(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: number, arg2: Time, arg3: ExpenseType, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, arg2, to_candid_ExpenseType_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, arg2, to_candid_ExpenseType_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateFarmTimeEntry(arg0: bigint, arg1: string | null, arg2: string | null, arg3: string): Promise<FarmTimeEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFarmTimeEntry(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFarmTimeEntry(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHarvestEntry(arg0: bigint, arg1: string, arg2: number, arg3: string, arg4: string, arg5: string): Promise<HarvestEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHarvestEntry(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHarvestEntry(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateIncome(arg0: bigint, arg1: number, arg2: Time, arg3: IncomeSource, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncome(arg0, arg1, arg2, to_candid_IncomeSource_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncome(arg0, arg1, arg2, to_candid_IncomeSource_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateInventoryItem(arg0: bigint, arg1: string, arg2: ItemType, arg3: bigint, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, arg1, to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, arg1, to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async updateWorker(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorker(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorker(arg0, arg1, arg2);
            return result;
        }
    }
    async uploadAttachmentToItem(arg0: bigint, arg1: string, arg2: string, arg3: Uint8Array): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAttachmentToItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAttachmentToItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async uploadFileAttachment(arg0: string, arg1: string, arg2: Uint8Array): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFileAttachment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFileAttachment(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseRecord_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseRecord): ExpenseRecord {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseType): ExpenseType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FarmTimeEntry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmTimeEntry): FarmTimeEntry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_IncomeRecord_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeRecord): IncomeRecord {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_IncomeSource_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeSource): IncomeSource {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerDailyRecord_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerDailyRecord): WorkerDailyRecord {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileAttachment]): FileAttachment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonthlyGoal]): MonthlyGoal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FarmTimeEntry]): FarmTimeEntry | null {
    return value.length === 0 ? null : from_candid_FarmTimeEntry_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HarvestEntry]): HarvestEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    description: string;
    category: _ExpenseType;
    amount: number;
    enteredBy: string;
}): {
    id: bigint;
    date: Time;
    description: string;
    category: ExpenseType;
    amount: number;
    enteredBy: string;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        category: from_candid_ExpenseType_n17(_uploadFile, _downloadFile, value.category),
        amount: value.amount,
        enteredBy: value.enteredBy
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    source: _IncomeSource;
    date: _Time;
    description: string;
    amount: number;
    enteredBy: string;
}): {
    id: bigint;
    source: IncomeSource;
    date: Time;
    description: string;
    amount: number;
    enteredBy: string;
} {
    return {
        id: value.id,
        source: from_candid_IncomeSource_n23(_uploadFile, _downloadFile, value.source),
        date: value.date,
        description: value.description,
        amount: value.amount,
        enteredBy: value.enteredBy
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    costPerUnit: number;
    name: string;
    itemType: _ItemType;
    quantity: bigint;
    enteredBy: string;
}): {
    id: bigint;
    costPerUnit: number;
    name: string;
    itemType: ItemType;
    quantity: bigint;
    enteredBy: string;
} {
    return {
        id: value.id,
        costPerUnit: value.costPerUnit,
        name: value.name,
        itemType: from_candid_ItemType_n28(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity,
        enteredBy: value.enteredBy
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workerId: bigint;
    arrivalTime: [] | [_Time];
    present: boolean;
    departureTime: [] | [_Time];
    date: _Time;
    timeOnFarm: [] | [bigint];
    enteredBy: string;
}): {
    workerId: bigint;
    arrivalTime?: Time;
    present: boolean;
    departureTime?: Time;
    date: Time;
    timeOnFarm?: bigint;
    enteredBy: string;
} {
    return {
        workerId: value.workerId,
        arrivalTime: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.arrivalTime)),
        present: value.present,
        departureTime: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.departureTime)),
        date: value.date,
        timeOnFarm: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.timeOnFarm)),
        enteredBy: value.enteredBy
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n39(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    workerId: bigint;
    arrivalTime: [] | [string];
    departureTime: [] | [string];
    date: string;
    hoursOnFarm: [] | [number];
    timestamp: bigint;
    workerName: string;
    enteredBy: Principal;
}): {
    id: bigint;
    status: string;
    workerId: bigint;
    arrivalTime?: string;
    departureTime?: string;
    date: string;
    hoursOnFarm?: number;
    timestamp: bigint;
    workerName: string;
    enteredBy: Principal;
} {
    return {
        id: value.id,
        status: value.status,
        workerId: value.workerId,
        arrivalTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.arrivalTime)),
        departureTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.departureTime)),
        date: value.date,
        hoursOnFarm: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.hoursOnFarm)),
        timestamp: value.timestamp,
        workerName: value.workerName,
        enteredBy: value.enteredBy
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fertilizers: null;
} | {
    transportation: null;
} | {
    other: null;
} | {
    equipment: null;
} | {
    labor: null;
} | {
    packaging: null;
}): ExpenseType {
    return "fertilizers" in value ? ExpenseType.fertilizers : "transportation" in value ? ExpenseType.transportation : "other" in value ? ExpenseType.other : "equipment" in value ? ExpenseType.equipment : "labor" in value ? ExpenseType.labor : "packaging" in value ? ExpenseType.packaging : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    local: null;
} | {
    market: null;
} | {
    wholesale: null;
}): IncomeSource {
    return "other" in value ? IncomeSource.other : "local" in value ? IncomeSource.local : "market" in value ? IncomeSource.market : "wholesale" in value ? IncomeSource.wholesale : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    equipment: null;
} | {
    peppers: null;
} | {
    fertilizer: null;
} | {
    pesticide: null;
}): ItemType {
    return "equipment" in value ? ItemType.equipment : "peppers" in value ? ItemType.peppers : "fertilizer" in value ? ItemType.fertilizer : "pesticide" in value ? ItemType.pesticide : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExpenseRecord>): Array<ExpenseRecord> {
    return value.map((x)=>from_candid_ExpenseRecord_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FarmTimeEntry>): Array<FarmTimeEntry> {
    return value.map((x)=>from_candid_FarmTimeEntry_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncomeRecord>): Array<IncomeRecord> {
    return value.map((x)=>from_candid_IncomeRecord_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerDailyRecord>): Array<WorkerDailyRecord> {
    return value.map((x)=>from_candid_WorkerDailyRecord_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n37(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseType): _ExpenseType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_IncomeSource_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncomeSource): _IncomeSource {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ItemType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    equipment: null;
} | {
    peppers: null;
} | {
    fertilizer: null;
} | {
    pesticide: null;
} {
    return value == ItemType.equipment ? {
        equipment: null
    } : value == ItemType.peppers ? {
        peppers: null
    } : value == ItemType.fertilizer ? {
        fertilizer: null
    } : value == ItemType.pesticide ? {
        pesticide: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseType): {
    fertilizers: null;
} | {
    transportation: null;
} | {
    other: null;
} | {
    equipment: null;
} | {
    labor: null;
} | {
    packaging: null;
} {
    return value == ExpenseType.fertilizers ? {
        fertilizers: null
    } : value == ExpenseType.transportation ? {
        transportation: null
    } : value == ExpenseType.other ? {
        other: null
    } : value == ExpenseType.equipment ? {
        equipment: null
    } : value == ExpenseType.labor ? {
        labor: null
    } : value == ExpenseType.packaging ? {
        packaging: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncomeSource): {
    other: null;
} | {
    local: null;
} | {
    market: null;
} | {
    wholesale: null;
} {
    return value == IncomeSource.other ? {
        other: null
    } : value == IncomeSource.local ? {
        local: null
    } : value == IncomeSource.market ? {
        market: null
    } : value == IncomeSource.wholesale ? {
        wholesale: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
